# https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle
# https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_ACTOR: ${{ github.actor }}
          OSSRH_ACTOR: ${{ secrets.OSSRH_ACTOR }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        with:
          semantic_version: ^23
          extra_plugins: |
            @semantic-release/git@^10
            @semantic-release/changelog@^6
            @semantic-release/exec@^6
            conventional-changelog-conventionalcommits@^7
            gradle-semantic-release-plugin@^1
