# https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle
# https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
      - uses: cachix/cachix-action@v16
        with:
          name: recap
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - uses: cycjimmy/semantic-release-action@v4
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_ACTOR: ${{ github.actor }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        with:
          semantic_version: ^24
          extra_plugins: |
            @semantic-release/git@^10
            @semantic-release/changelog@^6
            @semantic-release/exec@^6
            conventional-changelog-conventionalcommits@^8
            gradle-semantic-release-plugin@^1
